personal.unlockAccount("0xdc85a8429998bd4eef79307e556f70bb70d8caf1","bitcoin");

var bankPlus = web3.eth.contract([{"constant":false,"inputs":[],"name":"payBankTax","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"dividend","type":"address"}],"name":"payDividend","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":false,"inputs":[{"name":"customer","type":"address"}],"name":"withdraw50","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"taxContract","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":false,"inputs":[{"name":"recipient","type":"address"},{"name":"amount","type":"uint256"}],"name":"refund","outputs":[{"name":"","type":"string"}],"type":"function"},{"constant":false,"inputs":[],"name":"kill","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":false,"inputs":[{"name":"customer","type":"address"},{"name":"recipient","type":"address"},{"name":"amount","type":"uint256"}],"name":"sendMoney","outputs":[],"type":"function"},{"constant":false,"inputs":[],"name":"mortal","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"customer","type":"address"}],"name":"deposit","outputs":[],"type":"function"},{"anonymous":false,"inputs":[{"indexed":false,"name":"_dividend","type":"address"}],"name":"_deposit","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"_dividend","type":"address"}],"name":"_payDividend","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"_customer","type":"address"}],"name":"_withdraw50","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"_customer","type":"address"},{"indexed":false,"name":"_recipient","type":"address"},{"indexed":false,"name":"_amount","type":"address"}],"name":"_sendMoney","type":"event"}]).at("0x0d97ad1e473b907e0498cd1d492c96bf38290c95");

eth.sendTransaction({from: '0xdc85a8429998bd4eef79307e556f70bb70d8caf1', to: '0xebf91f1fb1df67709cc8346abcd9085c34c92a7e', value: web3.toWei(0.5, "ether")});

bankPlus.payBankTax.sendTransaction({from:"0xdc85a8429998bd4eef79307e556f70bb70d8caf1"});
bankPlus.payDividend.sendTransaction({from:"0xdc85a8429998bd4eef79307e556f70bb70d8caf1"});
//bankPlus.kill.sendTransaction({from:"0xdc85a8429998bd4eef79307e556f70bb70d8caf1"});

//eth.sendTransaction({from: '0xdc85a8429998bd4eef79307e556f70bb70d8caf1', to: '0x0d97ad1e473b907e0498cd1d492c96bf38290c95', value: web3.toWei(0.5, "ether")});
